version: "3"
services:
  # MySql database
  mysql_db:
    container_name: gobase_db
    image: mysql:5.7
    ports:
      - "3301:3306"
    environment:
      MYSQL_DATABASE: gobase
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: abc123
    volumes:
      - "./mysql:/docker-entrypoint-initdb.d"
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_general_ci"]
  # MySql database end

#  # Kafka
#  zookeeper:
#    container_name: zookeeper
#    image: wurstmeister/zookeeper:3.4.6
#    ports:
#      - "2181:2181"
#
#  kafka:
#    container_name: kafka
#    image: wurstmeister/kafka:2.12-2.3.0
#    hostname: dev-kafka
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: dev-kafka
#      KAFKA_ADVERTISED_PORT: 9092
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_CREATE_TOPICS: "random:5:2"
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
#    depends_on:
#      - zookeeper
#  # Kafka end